Switch to adaptive retries
OSError: unable to access bucket: 'commoncrawl' key: 'robots.txt' version: None error: An error occurred (SlowDown) when calling the GetObject operation (reached max retries: 4): Please reduce your request rate.