Create separate compression-specific layer to enable writing gzipped files. Fix #91 (#131)
* First working version

* Python 2.6 compatibility.

Gzip functionality broken in 2.6 because gzip tries to seek around the
file, which is not possible.

* implement separate s3 module

* minor update to S3 subsystem

* integrating new S3 subsystem into smart_open_lib.py

* work around absense of logging.NullHandler in Py2.6

* add docstrings for constants

* pass kwargs to S3 reader/writer constructors

* disable some verbose log statements

* wrap GzipFile in a closing for Py2.6

* get rid of unused imports

* be explicit about bytes vs str for Py3 compatibility

* disabling unsecured mode unit tests

* work around absence of unittest.skip in Python 2.6

* fix fout -> fin in tests

* read/write in binary mode when working via a codec

* get rid of is_gzip function

* fixup for be3bbb3

* bring back tests that "disappeared" during the rebase

* Work around Python 2.6 problem on Travis CI

AttributeError: 'module' object has no attribute 'test_smart_open'

* more "missing" tests

* Fix missing import

* s/_LOGGER/logger/g

* simplify null log handler code, no more Py2.6

* add pass statement to empty function